koszyk/urls.py
from django.urls import path
from . import views

app_name = 'koszyk'

urlpatterns = [
    path('', views.koszyk_wyswietl, name='koszyk_wyswietl'),
    path('add/<int:product_id>/',
         views.koszyk_add, name='koszyk_add'),
    path('remove/<int:product_id>/',
         views.koszyk_remove, name='koszyk_remove'),
]

mail/send_mail/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailer.urls')),
]

sklep/urls.py
from django.urls import path
from . import views
from django.urls import path

app_name = 'sklep'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('hello/', views.HelloView.as_view(), name='hello'),
]

sklep_internetowy/urls.py
from django.urls import include, path
#from rest_framework import routers
#from sklep import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from rest_framework_simplejwt import views as jwt_views
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView


# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.

app_name = 'sklep'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('koszyk/', include('koszyk.urls', namespace='koszyk')),
    path('zamowienia/', include('zamowienia.urls', namespace='zamowienia')),
    path('', include('sklep.urls', namespace='sklep')), #cos tu nie teges
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),

    #path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    #path('', views.product_list, name='product_list'),
    #path('<slug:category_slug>/', views.product_list(), name='product_list_by_category'), #usunac w razie w
    #path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'), #usunac w razei w
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

zamowienia/urls.py
from django.urls import path
from . import views


app_name = 'zamowienia'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

koszyk/models.py
from decimal import Decimal
from django.conf import settings
from sklep.models import Product


class Koszyk(object):
    def __init__(self, request):
        """
        Inicjalizacja koszyka na zakupy.
        """

        self.session = request.session
        koszyk = self.session.get(settings.KOSZYK_SESSION_ID)
        if not koszyk:
            # Zapis pustego koszyka na zakupy w sesji.
            koszyk = self.session[settings.KOSZYK_SESSION_ID] = {}
        self.koszyk = koszyk

    def __iter__(self):
        """
         Iteracja przez elementy koszyka na zakupy i pobranie produktów z bazy danych.
         """
        product_ids = self.koszyk.keys()
        products = Product.objects.filter(id__in=product_ids)

        koszyk = self.koszyk.copy()
        for product in products:
            koszyk[str(product.id)]['product'] = product

        for item in koszyk.values():
            item['price'] = Decimal(item['price'])
            item['total_price'] = item['price'] * item['quantity']
            yield item

    def __len__(self):
        """
        Obliczenie liczby wszystkich elementów w koszyku na zakupy.
        """
        return sum(item['quantity'] for item in self.koszyk.values())


    def add(self, product, quantity=1, override_quantity=False): #lub ovveride_quantity
        """
        Dodanie produktu do koszyka lub zmiana jego ilości.
        """
        product_id = str(product.id)
        if product_id not in self.koszyk:
            self.koszyk[product_id] = {'quantity': 0,
                                     'price': str(product.price)}
        if override_quantity: #tu tez
            self.koszyk[product_id]['quantity'] = quantity
        else:
            self.koszyk[product_id]['quantity'] = quantity
        self.save()

    def save(self):
        # Oznaczenie sesji jako "zmodyfikowanej", aby upewnić się o jej zapisaniu.
        self.session.modified = True

    def remove(self, product):
        """
        Usunięcie produktu z koszyka na zakupy.
        """
        product_id = str(product.id)
        if product_id in self.koszyk:
            del self.koszyk[product_id]
            self.save()

    def clear(self):
        del self.session[settings.KOSZYK_SESSION_ID]
        self.save()

    def get_total_price(self):
        return sum(Decimal(item['price']) * item['quantity'] for item in self.koszyk.values())

koszyk/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class KoszykAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

koszyk/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from koszyk.forms import KoszykAddProductForm
from koszyk.models import Koszyk
from sklep.models import Product

@require_POST
def koszyk_add(request, product_id):
    koszyk = Koszyk(request)
    product = get_object_or_404(Product, id=product_id)
    form = KoszykAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        koszyk.add(product=product,
                   quantity=cd['quantity'],
                   override_quantity=cd['update']) #lub update_quantity
    return redirect('koszyk:koszyk_wyswietl')


@require_POST
def koszyk_remove(request, product_id):
    koszyk = Koszyk(request)
    product = get_object_or_404(Product, id=product_id)
    koszyk.remove(product)
    return redirect('koszyk:koszyk_wyswietl')


def koszyk_wyswietl(request):
    koszyk = Koszyk(request)
    for item in koszyk:
        item['update_quantity_form'] = KoszykAddProductForm(initial={'quantity': item['quantity'],
                                                                     'override': True}) #usunac w razie w , bo brak reszty do tego
    return render(request, 'koszyk/szczegoly.html', {'koszyk':koszyk})

koszyk/templates/koszyk/szczegoly.html
{% extends "sklep/index.html" %}
{% load static %}

{% block title %}
  Twój koszyk
{% endblock %}

{% block content %}
  <h1>Twój koszyk</h1>
  <table class="koszyk">
    <thead>
      <tr>
        <th>Zdjęcie</th>
        <th>Produkt</th>
        <th>Ilość</th>
        <th>Usuń</th>
        <th>Cena jednostkowa</th>
        <th>Suma</th>
      </tr>
    </thead>
    <tbody>
      {% for item in koszyk %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}
                {% else %}{% static "obrazy/brakZdjecia.png" %}{% endif %}">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url "koszyk:koszyk_add" product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.override }}
                <input type="submit" value="Zmień">
                {% csrf_token %}
              </form>
            </td>
            <td>
              <form action="{% url "koszyk:koszyk_remove" product.id %}" method="post">
                <input type="submit" value="Usuń">
                {% csrf_token %}
              </form>
            </td>
            <td class="num">PLN {{ item.price }}</td>
            <td class="num">PLN {{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      <tr class="total">
        <td>Łącznie</td>
        <td colspan="4"></td>
        <td class="num">{{ koszyk.get_total_price }}PLN</td>
      </tr>
    </tbody>
  </table>
  <p class="text-right">
    <a href="{% url "sklep:product_list" %}" class="button light">Kontynuuj zakupy</a>
    <a href="{% url "zamowienia:order_create" %}" class="button">
      Złóż zamówienie</a>
  </p>
{% endblock %}